find_package(PkgConfig)

pkg_check_modules(PC_SDL2 REQUIRED sdl2)

find_path(SDL2_INCLUDE_DIR SDL.h HINTS ${PC_SDL2_INCLUDE_DIRS}
				${PC_SDL2_INCLUDEDIR} PATH_SUFFIXES SDL2)

find_library(SDL2_LIBRARY NAMES SDL2 libSDL2 HINTS ${PC_SDL2_LIBDIR}
				${PC_SDL2_LIBRARY_DIRS} )

set(SDL2_LIBRARIES ${SDL2_LIBRARY})
set(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})

find_package_handle_standard_args(SDL2 DEFAULT_MSG SDL2_LIBRARY SDL2_INCLUDE_DIR)
mark_as_advanced(SDL2_INCLUDE_DIR SDL2_LIBRARY)
